// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Storage$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Storage";
  readonly sourceName: "contracts/Storage.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"newNumber","type":"uint256"}],"name":"NumberStored","type":"event"},{"inputs":[{"internalType":"uint256","name":"_number","type":"uint256"}],"name":"setNumber","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5060c180601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80633fb5c1cb14602a575b5f5ffd5b603960353660046075565b603b565b005b5f8190556040518181527f3564ffb2fd8f93d7b0e9d1173ffdff5ee9775d860bfe82eaca0d0dbe07c8b6349060200160405180910390a150565b5f602082840312156084575f5ffd5b503591905056fea2646970667358221220fa9401b1a33984d777e2211085e00427f13b19a7a7d09d7c73c343eabffbc0c664736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106026575f3560e01c80633fb5c1cb14602a575b5f5ffd5b603960353660046075565b603b565b005b5f8190556040518181527f3564ffb2fd8f93d7b0e9d1173ffdff5ee9775d860bfe82eaca0d0dbe07c8b6349060200160405180910390a150565b5f602082840312156084575f5ffd5b503591905056fea2646970667358221220fa9401b1a33984d777e2211085e00427f13b19a7a7d09d7c73c343eabffbc0c664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Storage.sol";
  readonly buildInfoId: "solc-0_8_28-5c429e803032ee0eb2073c6471931dc10224c83f";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Storage"]: Storage$Type;
    ["contracts/Storage.sol:Storage"]: Storage$Type;
  }
}